include: package:very_good_analysis/analysis_options.yaml

custom_lint:
  rules:
    - missing_provider_scope: false

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart

  plugins:
    - custom_lint

  errors:
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore