name: flauncher
version: 1.0.0+1
publish_to: none
description: A flutter project
environment:
  sdk: '>=3.2.2 <4.0.0'
dependencies:
  blurhash_dart: ^1.2.1
  build_runner: any
  cached_network_image: ^3.3.0
  core:
    path: ../../packages/core
  cupertino_icons: ^1.0.2
  custom_lint: ^0.6.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_draft: ^1.0.2
  flutter_gen_runner: ^5.3.2
  flutter_hooks: ^0.20.3
  flutter_svg: ^2.0.4
  flutter_widgets:
    path: ../../packages/flutter_widgets
  get: ^4.6.6
  go_router: ^13.1.0
  go_router_builder: ^2.3.3
  hooks_riverpod: ^2.4.9
  image: ^4.1.7
  melos: ^3.1.0
  photos:
    path: ../../packages/photos
  riverpod_annotation: ^2.3.3
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

  very_good_analysis: ^5.1.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: ^1.0.4

flutter:
  assets:
    - assets/
    - assets/images/
  uses-material-design: true
