name: nav
description: nav
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  core:
    path: ../../packages/core
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  go_router: ^13.1.0
  go_router_builder: ^2.3.3
  hooks_riverpod: ^2.5.1
  photos:
    path: ../../packages/photos
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

  riverpod_generator: ^2.4.0
  very_good_analysis: ^5.1.0
  flutter_progress_hud: ^2.0.2

dependency_overrides:
  # Bug where on v13, PopScope is not invoked
  # https://github.com/flutter/flutter/issues/140869
  go_router: 12.1.3

flutter:
  uses-material-design: true
